function [state, options, optchanged] = OutputApiFunc(options, state, flag, api_endpoint)
    if nargin > 3 && ~isempty(api_endpoint) && api_endpoint ~= ""
        data = struct( ...
                'generation', state.Generation, ...
                'scores', state.Score, ...
                'best', state.Best, ...
                'last_improvement', state.LastImprovement ...
            );

        webwrite(api_endpoint, data);
    end
    optchanged = false;
end
